### ISSUE TITLE
CQL Support

### ISSUE THREAD

**Issue by antonyscerri** [textexploration/mtas#11]
Hi

It looks like MTAS doesn't support the full CQL language. This is based on the current specifications. 

For example the ability to search on a span using multiple attributes value pairs, eg [t="dog" & pos="NN"] as per https://www.sketchengine.eu/documentation/cql-basics/#boolean

The MTAS documentation also shows an example of doing this in a slightly different way (no square brackets) using something like: 

`t="dog" & POS="NN"
`

However this appears to generate an exception in the CQL parser "mtas.parser.cql.ParseException: Encountered "" at line 1, column 1.".

The closest I've come to doing this is using fullyalignedwith to repeatedly match each attribute value pair.

Thanks

Tony

**Comment by matthijsbrouwer** [comment]
Hi,
A query like [t="dog" & pos="NN"] should be no problem at all (see for example [query for t="coe" & pos="N"](https://www.middelnederlands.nl/zoeken/search/?type=cql&prefix=lemma&text=%5Bt%3D%22coe%22+%26+pos%3D%22N%22%5D#tab-documents) on a website using MTAS)

How did you create your index? Are you using MTAS as a Solr plugin? If so, what is your request to Solr?

Best

Matthijs
